#!/usr/bin/env python3

import sys
from math import *

def ducks_back(mini, a):
    i = 1.0
    while (1):
        if (proba_density(a, i / 60) - proba_density(a, 0) >= mini):
            return (i)
        i+=0.01

def aff_num(n):
    dix = n % 60 / 10
    unit = n % 10
    total_min = n / 60
    print("%dm %d%ds" %(total_min, dix, unit))

def proba_density(a, t):
    result = 0.0
    result = -a * exp(-t) - (4 - 3 * a) / 2 * exp(-2 * t) - (2 * a - 4) / 4 * exp(-4 * t)
    return (result)

def ducks(a):
    print("mean return time: %fs" %(a))
    print("standard deviation: %f" %(a))
    print("time after which 50% of the ducks are back: ", end='')
    n = ducks_back(0.5, a)
    aff_num(n)
    print("time after which 99% of the ducks are back: ", end='')
    n = ducks_back(0.99, a)
    aff_num(n)
    print("percentage of ducks back after 1 minute: %0.1f%%" %((proba_density(a, 1) - proba_density(a, 0)) * 100))
    print("percentage of ducks back after 2 minutes: %0.1f%%" %((proba_density(a, 2) - proba_density(a, 0)) * 100))

if (len(sys.argv) > 2 or len(sys.argv) < 2):
    print ("Error: not the right number of argument")
    exit(84)
else:
    try:
        if (sys.argv[1] == "-h"):
            print("USAGE\n\t./204ducks a\n\nDESCRIPTION\n\ta\tconstant")
            exit(84)
        a = float(sys.argv[1])
        if (a >= 0 and a <= 2.5):
            ducks(a)
            exit (0)
        else:
            print ("Error : value of a is not between 0 and 2.5 !")
            exit (84)
    except ValueError:
        print ("Error : Not the right type of parameter !")
        exit(84)
