#!/usr/bin/env python3

import sys
from math import *

if (len(sys.argv) == 0):
    print ("Error: not the right number of argument")
    exit(84)
else:
    try:
        if (len(sys.argv) == 2 and sys.argv[1] == "-h"):
            print("USAGE\n\t./207demography [...]\n\nDESCRIPTION\n\tcode1\tcountry code")
            exit(84)
        exit(0)
    except ValueError:
        print ("Error : Not the right type of parameter !")
        exit(84)
