#!/usr/bin/env python3

import sys
from math import *

def binomialelaw(d):
    i = 0
    p = d / (3600 * 8)
    n = 3500
    a = (coef_bino(n, i)) * (p**i) * ((1 - p)**(n - i))
    print("Binomial distribution:")
    print("%d -> %0.3f" %(i, a), end='')
    while (i < 50):
        i+=1
        if (i > 0 and (i % 6) != (0)):
            print("\t", end='')
        a = (coef_bino(n, i)) * (p**i) * ((1 - p)**(n - i))
        print("%d -> %0.3f" %(i, a), end='')
        if ((i + 1) % 6 == 0):
            print("")
    print("")
    print("overload: %0.1f%%" %(d))
    print("computation time: %0.2f ms" %(d))

def poissonlaw(d):
    i = 0
    l = 3500 * (d / (3600 * 8))
    a = exp(-l) * pow(l, i) / factorial(i)
    print("Poisson distribution:")
    print("%d -> %0.3f" %(i, a), end='')
    while (i < 50):
        i+=1
        if (i > 0 and (i % 6) != (0)):
            print("\t", end='')
        a = exp(-l) * pow(l, i) / factorial(i)
        print("%d -> %0.3f" %(i, a), end='')
        if ((i + 1) % 6 == 0):
            print("")
    print("")
    print("overload: %0.1f%%" %(d))
    print("computation time: %0.2f ms" %(d))

def coef_bino(n, k):
    a = factorial(n)
    b = factorial(k)
    c = factorial(n - k)
    res = a // (b * c)
    return (res)

if (len(sys.argv) > 3 or len(sys.argv) < 2):
    print ("Error: not the right number of argument")
    exit(84)
else:
    try:
        if (len(sys.argv) == 2 and sys.argv[1] == "-h"):
            print("USAGE\n\t./203hotline [n k | d]\n\nDESCRIPTION\n\tn\tn value for the computation of (n k)\n\tk\tk value for the computation of (n k)\n\td\taverage duration of calls (in seconds)")
            exit(84)
        elif(len(sys.argv) == 2):
            d = int(sys.argv[1])
            binomialelaw(d)
            print("")
            poissonlaw(d)
            exit(0)
        elif(len(sys.argv) == 3):
            n = int(sys.argv[1])
            k = int(sys.argv[2])
            print("%d-combination of a %d set:\n%d" %(k, n, coef_bino(n, k)))
            exit(0)
    except ValueError:
        print ("Error : Not the right type of parameter !")
        exit(84)
