#!/usr/bin/env python3

import sys
import math

mode = "normal"
try:
    s = float(sys.argv[2])
    u = float(sys.argv[1])
    if len(sys.argv) == 4:
        a = int(sys.argv[3])
        mode = "bellows"
    if len(sys.argv) == 5:
        a = int(sys.argv[3])
        b = int(sys.argv[4])
        mode = "between"
except Exception as e:
    print(e)
    exit(84)


l = [(1.0/ (s * math.sqrt(2.0 * math.pi))) * math.exp(- (math.pow(i/100 - u, 2))/ (2.0 * math.pow(s, 2))) for i in range(0, 20100)]
if mode == "normal":
    for i in range(0, 2000, 100):
        print(str(i/10) + " " + "%0.5f" % l[i])
if mode == "bellows":
    print("%0.1f" % (sum(l[:a*100]) * 100) + "% of people have an IQ inferior to " + str(int(a)))
if mode == "between":
    print("%0.1f" % (math.fsum(l[a*100:b*100]) * 100) + "%% of people have an IQ between %s" % int(a) + " and %s" % int(b) )
