#!/bin/sh

checkArgs () {
    if [ -z "$1" ]; then
  echo "USAGE: $0 filename
filename : line by line db file - each entry must be separated with a blank line
result : 1 line by record, order by field name">&2
  exit 1
  fi
}

checkParam () {
  file_name="$1"
  if [ -e "$file_name" ]; then
    if [ -f $file_name ]
      then
      if [ -w "$file_name" ]; then
        exit 0
      else
        echo "ERROR: $file_name is not writable">&2
        exit 1
      fi
    else
      echo "ERROR: $file_name is not a file">&2
      exit 1
    fi
    else
      echo "ERROR: $file_name : file not found">&2
      exit 1
  fi
}

checkArgs "$1"
checkParam "$1"