#!/bin/sh

checkArgs () {
    if [ -z "$1" ]; then
	echo "USAGE: $0 number">&2
	echo "Compute factorial of a number">&2
	exit 1
    fi
}

checkNum () {
  if [[ "${1}" =~ ^[]?[0-9]+$ ]]; then
    facNum "$1"
    exit 0
  else
    echo "Error">&2
    exit 1
  fi
}

facNum () {
  fact="$1"
  rep=1
  counter=0
  while [ $fact -ne $counter ]
  do
    counter=`expr $counter + 1`
    rep=`expr $rep \* $counter`
    done
    echo "$rep"
}

checkArgs "$1"
checkNum "$1"